    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
        <div class="lime-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span class="footer-text float-left" id="kep"><?php echo $year; ?> © <?php echo locale('madeby'); ?> <a href="https://discord.io/ezApps">Tyler</a></span>
                        <span class="footer-text float-right" id="ripl"><a href="https://github.com/ezAppsDev/Application-System">v<?php echo $version; ?></a></span>
                    </div>
                </div>
            </div>
        </div>
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
