    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
        <div class="lime-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span class="footer-text"><?php echo $year; ?> © <a href="https://discord.io/ezApps">Tyler Development Services</a></span>
                    </div>
                </div>
            </div>
        </div>
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
    <!-- DO NOT REMOVE, MODIFY, OR ADD TO THIS IN ANYWAY. YOU ARE NOT ALLOWED TO REMOVE THE COPYRIGHT, OR BACKLINKS. -->
